version: '3.5'

services:
  postgressSQLForTestTask:
    container_name: postgressSQLForTestTask
    restart: unless-stopped
    image: postgres:12
    env_file:
      - .env
    ports:
      - 3032:5432
    volumes:
      - data:/var/lib/postgresql/data

#  upload_frontend:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./frontend
#    container_name: upload_frontend
#    restart: unless-stopped
#    command: npm run start
#    stdin_open: true
#    tty: true
#    ports:
#      - '3000:3000'

#  upload_backend:
#    build:
#      dockerfile: Dockerfile
#      context: ./upload_backend
#    container_name: upload_backend
#    command:
#      - dotnet run
#    # For debug only
#    ports:
#      - 5001:5001
volumes:
  data:
