version: '3.5'

services:
  postgressSQLForTestTask:
    container_name: postgressSQLForTestTask
    restart: unless-stopped
    image: postgres:12
    env_file:
      - .env
    ports:
      - 3032:5432
    volumes:
      - data:/var/lib/postgresql/data

  #upload_frontend:
  #  build:
  #    dockerfile: Dockerfile.dev
  #    context: ./frontend
  #  container_name: upload_frontend
  #  restart: unless-stopped
  #  #depends_on:
  #  #  - ga_backend_orchestrator
  #  # For debug only
  #  ports:
  #    - 3000:3000
  #  volumes:
  #    - ./dev.default-frontend.conf:/etc/nginx/conf.d/default.conf

  #upload_backend:
  #  build:
  #    dockerfile: Dockerfile.dev
  #    context: ./frontend
  #  container_name: upload_backend
  #  # For debug only
  #  ports:
  #    - 5001:5001
volumes:
  data:
