// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication;

namespace upload_backend.Migrations
{
    [DbContext(typeof(UploadDBContext))]
    partial class UploadDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebApplication.models.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswersType")
                        .HasColumnType("integer");

                    b.Property<bool>("CaseSensitivity")
                        .HasColumnType("boolean");

                    b.Property<bool>("ContainCyrillic")
                        .HasColumnType("boolean");

                    b.Property<bool>("ContainSpecialCharacters")
                        .HasColumnType("boolean");

                    b.Property<bool>("ContainsNumbers")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("ImagesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
